version: "3.7"

services:
  app:
    container_name: "go-clean-architecture"
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - $GOPATH/pkg/mod/cache:/go/pkg/mod/cache
    env_file:
      - .env
    networks:
      - main
    depends_on:
      - postgres

  postgres:
    container_name: "postgres"
    image: "postgres:12.2-alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: bank
    volumes:
      - ./_scripts/postgres:/docker-entrypoint-initdb.d
    networks:
      - main

networks:
  main:
